---
image: "sabayon/builder-amd64"
env:
  - ACCEPT_LICENSE=*
prelude:
  - "source /etc/profile"
  - "equo install virtual/jre:1.8 dev-libs/libdbusmenu dev-python/pip"
steps:
  - "source /etc/profile"
  - emerge pycharm-professional
